apiVersion: v1
kind: Service
metadata:
  name: front-end
spec:
  type: LoadBalancer
  selector:
    app: front-end
  ports:
  - port: 3333
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
spec:
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
    spec:
      nodeSelector:
        key: front-end
      containers:
      - name: front-end
        image: niyazidocker/front-end
        resources:
          limits:
            memory: "550Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000
